# Generated by Django 5.2.9 on 2025-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='print_type',
            field=models.CharField(default='B&W', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='side_type',
            field=models.CharField(default='1-Side', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(max_length=50),
        ),
    ]
