# Generated by Django 5.2.9 on 2025-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_print_type_alter_order_side_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='print_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='side_type',
            field=models.CharField(max_length=50),
        ),
    ]
