# Generated by Django 5.2.9 on 2025-12-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_print_type_alter_order_side_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='print_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='side_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
