# Generated by Django 5.2.9 on 2025-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_copies_remove_order_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='print_type',
            field=models.CharField(default='bw', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='In Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
