# Generated by Django 5.2.9 on 2025-12-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_copies_remove_order_print_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
