# Generated by Django 5.2.9 on 2025-12-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_copies_order_document_order_print_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='side_type',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
