# Generated by Django 5.2.9 on 2025-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_side_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='short_description',
        ),
        migrations.AddField(
            model_name='service',
            name='theme_color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Ready', 'Order is Ready'), ('Delivered', 'Delivered')], default='In Progress', max_length=20),
        ),
    ]
