# Generated by Django 5.2.9 on 2025-12-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='print_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='side_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
