# Generated by Django 5.2.9 on 2025-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_service_short_description_service_theme_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='In Progress', max_length=20),
        ),
    ]
