# Generated by Django 5.2.9 on 2025-12-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_copies_order_print_type_order_side_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='side_type',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
