# Generated by Django 5.2.10 on 2026-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_order_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='temp_file_path',
            field=models.CharField(blank=True, help_text='Temporary path for PDF during payment', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='temp_image_path',
            field=models.CharField(blank=True, help_text='Temporary path for Image during payment', max_length=500, null=True),
        ),
    ]
