# Generated by Django 5.2.10 on 2026-01-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_order_temp_file_path_order_temp_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Maintenance Mode Enabled')),
                ('message', models.TextField(default='We are upgrading our system to serve you better. We will be back shortly!', help_text='Message to display to users on the maintenance page.')),
                ('expected_duration', models.CharField(default='2 hours', help_text="Expected duration text (e.g., '2 hours', '30 minutes')", max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Settings',
                'verbose_name_plural': 'Maintenance Settings',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='temp_file_path',
        ),
        migrations.RemoveField(
            model_name='order',
            name='temp_image_path',
        ),
    ]
