# Generated by Django 5.2.10 on 2026-01-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_maintenancesettings_remove_order_temp_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_delivery_boy',
            field=models.BooleanField(default=False, verbose_name='Is Delivery Partner'),
        ),
    ]
