# Generated by Django 5.2.10 on 2026-01-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_userprofile_is_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, help_text='Contact number for this specific order', max_length=15, null=True),
        ),
    ]
