# Generated by Django 5.2.10 on 2026-01-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_order_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name for this specific order', max_length=150, null=True),
        ),
    ]
