# Generated by Django 5.2.10 on 2026-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
